export const MOCK_LISTINGS = [
  {
    id: "mock-1",
    title: "2019 Toyota Prius - Excellent Condition",
    description: "Well-maintained Prius with low mileage. Perfect for rideshare or daily commute. Mongolian owner, all records available. Шинэ шиг машин.",
    category: "cars",
    price: 8500,
    price_type: "negotiable",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800"],
    contact_phone: "(312) 555-1234",
    contact_email: "bold@gmail.com",
    status: "active",
    is_featured: true,
    views: 342,
    saves: 28,
    poster_name: "Болд Б.",
    poster_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
    car_make: "Toyota",
    car_model: "Prius",
    car_year: 2019,
    car_mileage: 45000,
    car_transmission: "automatic",
    car_fuel: "hybrid",
    car_condition: "excellent",
    tags: ["toyota", "prius", "hybrid", "chicago"],
    created_date: "2026-05-06T10:00:00Z"
  },
  {
    id: "mock-2",
    title: "CDL Driver Needed - $1,800/week",
    description: "Mongolian-owned trucking company hiring CDL-A drivers. OTR and regional routes available. Монгол компани жолооч авна. Сайн цалинтай.",
    category: "jobs",
    price: 1800,
    price_type: "weekly",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800"],
    contact_phone: "(773) 555-5678",
    status: "active",
    is_featured: true,
    views: 567,
    saves: 89,
    poster_name: "NomadTruck LLC",
    poster_avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
    job_company: "NomadTruck LLC",
    job_salary_min: 1800,
    job_salary_max: 2400,
    job_type: "full-time",
    job_schedule: "Mon-Fri, OTR available",
    job_benefits: "Health insurance, Paid time off",
    tags: ["cdl", "driver", "trucking", "chicago"],
    created_date: "2026-05-07T08:00:00Z"
  },
  {
    id: "mock-3",
    title: "2BR Apartment - Uptown Chicago",
    description: "Spacious 2 bedroom apartment in Uptown. Close to Red Line. Utilities included. Mongolian neighbors. 2 өрөө байр, бүх зардал орсон.",
    category: "housing",
    price: 1200,
    price_type: "monthly",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"],
    contact_phone: "(312) 555-9012",
    status: "active",
    is_featured: false,
    views: 234,
    saves: 45,
    poster_name: "Сарнай Д.",
    poster_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    housing_bedrooms: 2,
    housing_bathrooms: 1,
    housing_furnished: false,
    housing_utilities: "All included",
    housing_lease: "12 months",
    housing_type: "apartment",
    tags: ["apartment", "uptown", "chicago", "2br"],
    created_date: "2026-05-05T14:00:00Z"
  },
  {
    id: "mock-4",
    title: "Mongolian New Year Celebration - Tsagaan Sar 2026",
    description: "Join us for the biggest Mongolian New Year celebration in the Midwest! Traditional food, music, dancing, and cultural performances. Цагаан сарын баярын арга хэмжээ.",
    category: "events",
    price: 25,
    price_type: "fixed",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800"],
    status: "active",
    is_featured: true,
    views: 1203,
    saves: 156,
    poster_name: "MACA Chicago",
    poster_avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200",
    event_date: "2026-06-15T18:00:00Z",
    event_venue: "Hyatt Regency Chicago",
    event_ticket_price: 25,
    event_organizer: "Mongolian American Cultural Association",
    tags: ["tsagaan sar", "event", "chicago", "culture"],
    created_date: "2026-05-01T09:00:00Z"
  },
  {
    id: "mock-5",
    title: "iPhone 15 Pro Max - Like New",
    description: "256GB, Natural Titanium. 2 months old, perfect condition. Comes with original box and accessories. Шинэ утас.",
    category: "electronics",
    price: 850,
    price_type: "fixed",
    location_city: "Los Angeles",
    location_state: "CA",
    images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800"],
    contact_phone: "(213) 555-3456",
    status: "active",
    views: 189,
    saves: 34,
    poster_name: "Тэмүүлэн Г.",
    poster_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    tags: ["iphone", "electronics", "la"],
    created_date: "2026-05-07T12:00:00Z"
  },
  {
    id: "mock-6",
    title: "Part-time Cashier - Mongolian Restaurant",
    description: "Looking for a part-time cashier for our Mongolian restaurant. Must speak Mongolian and English. Flexible hours. Монгол ресторанд кассчин авна.",
    category: "jobs",
    price: 17,
    price_type: "hourly",
    location_city: "Seattle",
    location_state: "WA",
    images: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800"],
    status: "active",
    views: 98,
    saves: 12,
    poster_name: "Khaan's Kitchen",
    poster_avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
    job_company: "Khaan's Kitchen",
    job_salary_min: 17,
    job_salary_max: 20,
    job_type: "part-time",
    job_schedule: "Flexible, weekends required",
    tags: ["restaurant", "part-time", "seattle"],
    created_date: "2026-05-06T16:00:00Z"
  },
  {
    id: "mock-7",
    title: "Tax Preparation Service - Монгол хэлээр",
    description: "Professional tax preparation in Mongolian and English. Individual and business returns. Free consultation. IRS enrolled agent. Татварын үйлчилгээ Монгол хэлээр.",
    category: "services",
    price: 150,
    price_type: "fixed",
    location_city: "Virginia",
    location_state: "VA",
    images: ["https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800"],
    contact_phone: "(703) 555-7890",
    status: "active",
    is_featured: true,
    views: 445,
    saves: 67,
    poster_name: "Ганбаатар CPA",
    poster_avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200",
    tags: ["tax", "cpa", "mongolian", "virginia"],
    created_date: "2026-05-04T11:00:00Z"
  },
  {
    id: "mock-8",
    title: "2021 Honda Civic - Low Miles",
    description: "Clean title, one owner, regular maintenance. Great gas mileage. Цэвэр Honda Civic зарна.",
    category: "cars",
    price: 15000,
    price_type: "negotiable",
    location_city: "New York",
    location_state: "NY",
    images: ["https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800"],
    contact_phone: "(718) 555-2345",
    status: "active",
    views: 278,
    saves: 41,
    poster_name: "Батбаяр Н.",
    poster_avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    car_make: "Honda",
    car_model: "Civic",
    car_year: 2021,
    car_mileage: 28000,
    car_transmission: "automatic",
    car_fuel: "gasoline",
    car_condition: "excellent",
    tags: ["honda", "civic", "nyc"],
    created_date: "2026-05-07T15:00:00Z"
  },
  {
    id: "mock-9",
    title: "Room for Rent - Near Koreatown LA",
    description: "Private room in shared apartment. Near Koreatown. Close to buses and metro. Нэг өрөө түрээслүүлнэ.",
    category: "housing",
    price: 750,
    price_type: "monthly",
    location_city: "Los Angeles",
    location_state: "CA",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    status: "active",
    views: 167,
    saves: 23,
    poster_name: "Оюунаа М.",
    poster_avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    housing_bedrooms: 1,
    housing_bathrooms: 1,
    housing_furnished: true,
    housing_type: "room",
    housing_lease: "6 months",
    tags: ["room", "la", "koreatown"],
    created_date: "2026-05-06T09:00:00Z"
  },
  {
    id: "mock-10",
    title: "Mongolian BBQ Night - Community Event",
    description: "Monthly community BBQ gathering! Bring your family and friends. Free for all Mongolians! Сар бүрийн нийтийн шарсан мах.",
    category: "events",
    price: 0,
    price_type: "free",
    location_city: "Seattle",
    location_state: "WA",
    images: ["https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800"],
    status: "active",
    views: 432,
    saves: 78,
    poster_name: "Seattle Mongols",
    poster_avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200",
    event_date: "2026-05-20T17:00:00Z",
    event_venue: "Woodland Park, Seattle",
    event_ticket_price: 0,
    event_organizer: "Seattle Mongolian Community",
    tags: ["bbq", "community", "seattle", "free"],
    created_date: "2026-05-03T10:00:00Z"
  }
];

export const MOCK_GROUPS = [
  {
    id: "grp-1",
    name: "Chicago Mongolians",
    description: "The largest Mongolian community group in Chicago. Share news, events, jobs, and connect with fellow Mongolians. Чикагогийн Монголчуудын бүлэг.",
    cover_image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800",
    avatar: "🏙️",
    category: "community",
    city: "Chicago",
    member_count: 2847,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-2",
    name: "CDL Drivers USA - Монгол",
    description: "For Mongolian CDL drivers across the US. Share routes, companies, tips, and job openings. CDL жолоочдын бүлэг.",
    cover_image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800",
    avatar: "🚛",
    category: "professional",
    member_count: 1563,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-3",
    name: "Seattle Mongolian Community",
    description: "Connecting Mongolians in the Seattle/Tacoma area. Events, meetups, and community support. Сиатл Монголчууд.",
    cover_image: "https://images.unsplash.com/photo-1502175353174-a7a70e73b362?w=800",
    avatar: "🌲",
    category: "community",
    city: "Seattle",
    member_count: 892,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-4",
    name: "Mongolian Students USA",
    description: "Support network for Mongolian students studying in the US. Scholarships, advice, and networking. Монгол оюутнууд.",
    cover_image: "https://images.unsplash.com/photo-1523050854058-8df90110c476?w=800",
    avatar: "🎓",
    category: "education",
    member_count: 1245,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-5",
    name: "Mongolian Entrepreneurs",
    description: "Business owners and aspiring entrepreneurs. Share experiences, find partners, and grow together. Монгол бизнес эрхлэгчид.",
    cover_image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800",
    avatar: "💼",
    category: "business",
    member_count: 678,
    is_verified: false,
    privacy: "public"
  }
];

export const MOCK_BUSINESSES = [
  {
    id: "biz-1",
    name: "Khaan's Kitchen",
    description: "Authentic Mongolian restaurant serving traditional dishes. Buuz, khuushuur, tsuivan, and more. Жинхэнэ Монгол хоол.",
    category: "restaurant",
    logo: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=200",
    banner: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    city: "Chicago",
    state: "IL",
    phone: "(312) 555-8888",
    hours: "Mon-Sat 11am-10pm, Sun 12pm-8pm",
    rating: 4.7,
    review_count: 234,
    is_verified: true,
    is_premium: true,
    tags: ["mongolian", "restaurant", "buuz"]
  },
  {
    id: "biz-2",
    name: "NomadTruck LLC",
    description: "Mongolian-owned trucking company. OTR and regional routes. Always hiring CDL-A drivers with good pay and benefits.",
    category: "trucking",
    logo: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=200",
    banner: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800",
    city: "Chicago",
    state: "IL",
    phone: "(773) 555-5678",
    hours: "Mon-Fri 8am-6pm",
    rating: 4.3,
    review_count: 89,
    is_verified: true,
    is_premium: true,
    tags: ["trucking", "cdl", "jobs"]
  },
  {
    id: "biz-3",
    name: "Ганбаатар CPA Services",
    description: "Full-service accounting and tax preparation. Mongolian and English speaking. Individual and business returns.",
    category: "tax",
    logo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200",
    banner: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800",
    city: "Virginia",
    state: "VA",
    phone: "(703) 555-7890",
    hours: "Mon-Fri 9am-5pm, Sat by appointment",
    rating: 4.9,
    review_count: 156,
    is_verified: true,
    is_premium: false,
    tags: ["tax", "cpa", "accounting"]
  },
  {
    id: "biz-4",
    name: "Nomad Beauty Salon",
    description: "Premium beauty salon specializing in Asian hair care. Mongolian owned and operated. Гоо сайхны салон.",
    category: "salon",
    logo: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=200",
    banner: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800",
    city: "Los Angeles",
    state: "CA",
    phone: "(213) 555-4567",
    hours: "Tue-Sun 10am-7pm",
    rating: 4.6,
    review_count: 78,
    is_verified: true,
    is_premium: true,
    tags: ["salon", "beauty", "hair"]
  }
];

export const CATEGORIES = [
  { id: "jobs", label: "Jobs", labelMn: "Ажил", icon: "Briefcase" },
  { id: "housing", label: "Housing", labelMn: "Байр", icon: "Home" },
  { id: "events", label: "Events", labelMn: "Арга хэмжээ", icon: "Calendar" },
  { id: "cars", label: "Cars", labelMn: "Машин", icon: "Car" },
  { id: "services", label: "Services", labelMn: "Үйлчилгээ", icon: "Wrench" },
  { id: "electronics", label: "Electronics", labelMn: "Электроник", icon: "Smartphone" },
  { id: "community", label: "Community", labelMn: "Нийгэмлэг", icon: "Users" }
];

// Authentic community discussions — emotionally varied: urgent, quiet, helpful, lonely, active
export const MOCK_DISCUSSIONS = [
  {
    id: "disc-1",
    author_name: "Мөнхбаяр О.",
    author_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop&crop=face",
    content: "Маргааш 7 цагт Чикагоос Денвер явах хүн байна уу? Хойр хүн, тэшүүр байна. Бензиний мөнгийг хуваана.",
    city: "Chicago",
    tag: "Ride Share",
    tone: "urgent",
    reply_count: 3,
    views: 61,
    likes: 4,
    created_date: new Date(Date.now() - 38 * 60000).toISOString(),
    top_reply: {
      name: "Батхүү Д.",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=32&fit=crop&crop=face",
      text: "Бид хойр явна! DM илгээгээрэй."
    }
  },
  {
    id: "disc-2",
    author_name: "Түмэнбаяр Ц.",
    author_avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=80&h=80&fit=crop&crop=face",
    content: "Сая сар Шикаго ирсэн. Ямар монгол хүн танилцтай байна. Канад газар, ямар сайхан уу? Учраас гээр байна 🙏",
    city: "Chicago",
    tag: "New Here",
    tone: "lonely",
    reply_count: 8,
    views: 143,
    likes: 14,
    created_date: new Date(Date.now() - 1.5 * 3600000).toISOString(),
    top_reply: {
      name: "Дашдъямба О.",
      avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=32&fit=crop&crop=face",
      text: "Харагтай! Бид ч Pilsen дуур оросин. DM хийгээрэй, цай ууужия."
    }
  },
  {
    id: "disc-3",
    author_name: "Ариунаа С.",
    author_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop&crop=face",
    content: "Арлингтоны ойролцоо өрөөний нөхөр хайж байна. Эмэгтэй, ажилтай, тамхи татдаггүй. $750/mo хуртал.",
    city: "Virginia",
    tag: "Roommate",
    tone: "practical",
    reply_count: 11,
    views: 209,
    likes: 19,
    created_date: new Date(Date.now() - 2.5 * 3600000).toISOString(),
    top_reply: {
      name: "Номин Г.",
      avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=32&fit=crop&crop=face",
      text: "Манайд нэг өрөө гарна Мэй сүүлд. DM хийгээрэй!"
    }
  },
  {
    id: "disc-4",
    author_name: "Ганзориг Б.",
    author_avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop&crop=face",
    content: "Чикагод хамгийн амттай монгол хоол заадаг газар аль вэ? Аилчлагч найздаа зориулж захиалга хийх гэж байна 🥩",
    city: "Chicago",
    tag: "Food",
    tone: "active",
    reply_count: 18,
    views: 374,
    likes: 29,
    created_date: new Date(Date.now() - 5 * 3600000).toISOString(),
    top_reply: {
      name: "Хаан's Kitchen",
      avatar: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=32&fit=crop",
      text: "Манай ресторан буузаараа алдартай! (312) 555-8888"
    }
  },
  {
    id: "disc-5",
    author_name: "Пүрэвсүрэн Д.",
    author_avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop&crop=face",
    content: "Монголоос хүн ирэх гэж байна — JFK дамжна. Нислэгийн хоорондох 6 цаг зав байна. Хотоор аялж болох уу? Зааж өгч чадах хүн бий юу?",
    city: "New York",
    tag: "Help",
    tone: "lonely",
    reply_count: 0,
    views: 47,
    likes: 2,
    created_date: new Date(Date.now() - 7 * 3600000).toISOString(),
    top_reply: null
  },
  {
    id: "disc-6",
    author_name: "Оюунцэцэг Л.",
    author_avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop&crop=face",
    content: "CDL авах сургалтанд хамрагдсан хүн бэй? Ямар сургуульд сурав, ямар компани эхлэх нь дээр вэ? Туршлагаасаа хуваалцаарай 🙏",
    city: "Chicago",
    tag: "CDL",
    tone: "active",
    reply_count: 26,
    views: 512,
    likes: 41,
    created_date: new Date(Date.now() - 11 * 3600000).toISOString(),
    top_reply: {
      name: "NomadTruck LLC",
      avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=32&fit=crop&crop=face",
      text: "Бид CDL дадлагад олгодог! Холбоо бариарай."
    }
  },
  {
    id: "disc-7",
    author_name: "Мөнхтуяа В.",
    author_avatar: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=80&h=80&fit=crop&crop=face",
    content: "Сиэтлд энэ долоо хоногт хаана яваа сонин зүйл болж байна? 🌲 Тэгш нийтийн арга хэмжээ мэдэх хӯн бий юу?",
    city: "Seattle",
    tag: "Events",
    tone: "quiet",
    reply_count: 2,
    views: 88,
    likes: 7,
    created_date: new Date(Date.now() - 16 * 3600000).toISOString(),
    top_reply: {
      name: "Seattle Mongols",
      avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=32&fit=crop",
      text: "Нямдугаар Woodland Park-т BBQ болно."
    }
  },
  {
    id: "disc-8",
    author_name: "Батболд Т.",
    author_avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop&crop=face",
    content: "LA-д монгол эмч эсвэл монгол хэлтэй эмнэлэг байдаг уу? Даатгалгүй ч болно.",
    city: "Los Angeles",
    tag: "Ask",
    tone: "lonely",
    reply_count: 0,
    views: 33,
    likes: 0,
    created_date: new Date(Date.now() - 22 * 3600000).toISOString(),
    top_reply: null
  }
];

export const ICONS = {
  Car: "🚗",
  Briefcase: "💼",
  Home: "🏠",
  Wrench: "🔧",
  Calendar: "📅",
  Smartphone: "📱",
  Users: "👥"
};

export const TRENDING_SEARCHES = [
  "CDL ажил Chicago",
  "apartment near me",
  "Монгол ресторан",
  "part time job",
  "машин зарна",
  "room for rent LA",
  "trucking company",
  "tax preparation"
];

export const CITIES = [
  { name: "Chicago", state: "IL", count: 1245 },
  { name: "Los Angeles", state: "CA", count: 876 },
  { name: "Seattle", state: "WA", count: 543 },
  { name: "New York", state: "NY", count: 432 },
  { name: "Virginia", state: "VA", count: 321 },
  { name: "Korea", state: "", count: 234 },
  { name: "Europe", state: "", count: 187 }
];