export const MOCK_LISTINGS = [
  {
    id: "mock-1",
    title: "2019 Toyota Prius - Excellent Condition",
    description: "Well-maintained Prius with low mileage. Perfect for rideshare or daily commute. Mongolian owner, all records available. Шинэ шиг машин.",
    category: "cars",
    price: 8500,
    price_type: "negotiable",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800"],
    contact_phone: "(312) 555-1234",
    contact_email: "bold@gmail.com",
    status: "active",
    is_featured: true,
    views: 342,
    saves: 28,
    poster_name: "Болд Б.",
    poster_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
    car_make: "Toyota",
    car_model: "Prius",
    car_year: 2019,
    car_mileage: 45000,
    car_transmission: "automatic",
    car_fuel: "hybrid",
    car_condition: "excellent",
    tags: ["toyota", "prius", "hybrid", "chicago"],
    created_date: "2026-05-06T10:00:00Z"
  },
  {
    id: "mock-2",
    title: "CDL Driver Needed - $1,800/week",
    description: "Mongolian-owned trucking company hiring CDL-A drivers. OTR and regional routes available. Монгол компани жолооч авна. Сайн цалинтай.",
    category: "jobs",
    price: 1800,
    price_type: "weekly",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800"],
    contact_phone: "(773) 555-5678",
    status: "active",
    is_featured: true,
    views: 567,
    saves: 89,
    poster_name: "NomadTruck LLC",
    poster_avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200",
    job_company: "NomadTruck LLC",
    job_salary_min: 1800,
    job_salary_max: 2400,
    job_type: "full-time",
    job_schedule: "Mon-Fri, OTR available",
    job_benefits: "Health insurance, Paid time off",
    tags: ["cdl", "driver", "trucking", "chicago"],
    created_date: "2026-05-07T08:00:00Z"
  },
  {
    id: "mock-3",
    title: "2BR Apartment - Uptown Chicago",
    description: "Spacious 2 bedroom apartment in Uptown. Close to Red Line. Utilities included. Mongolian neighbors. 2 өрөө байр, бүх зардал орсон.",
    category: "housing",
    price: 1200,
    price_type: "monthly",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800"],
    contact_phone: "(312) 555-9012",
    status: "active",
    is_featured: false,
    views: 234,
    saves: 45,
    poster_name: "Сарнай Д.",
    poster_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    housing_bedrooms: 2,
    housing_bathrooms: 1,
    housing_furnished: false,
    housing_utilities: "All included",
    housing_lease: "12 months",
    housing_type: "apartment",
    tags: ["apartment", "uptown", "chicago", "2br"],
    created_date: "2026-05-05T14:00:00Z"
  },
  {
    id: "mock-4",
    title: "Mongolian New Year Celebration - Tsagaan Sar 2026",
    description: "Join us for the biggest Mongolian New Year celebration in the Midwest! Traditional food, music, dancing, and cultural performances. Цагаан сарын баярын арга хэмжээ.",
    category: "events",
    price: 25,
    price_type: "fixed",
    location_city: "Chicago",
    location_state: "IL",
    images: ["https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800"],
    status: "active",
    is_featured: true,
    views: 1203,
    saves: 156,
    poster_name: "MACA Chicago",
    poster_avatar: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=200",
    event_date: "2026-06-15T18:00:00Z",
    event_venue: "Hyatt Regency Chicago",
    event_ticket_price: 25,
    event_organizer: "Mongolian American Cultural Association",
    tags: ["tsagaan sar", "event", "chicago", "culture"],
    created_date: "2026-05-01T09:00:00Z"
  },
  {
    id: "mock-5",
    title: "iPhone 15 Pro Max - Like New",
    description: "256GB, Natural Titanium. 2 months old, perfect condition. Comes with original box and accessories. Шинэ утас.",
    category: "electronics",
    price: 850,
    price_type: "fixed",
    location_city: "Los Angeles",
    location_state: "CA",
    images: ["https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800"],
    contact_phone: "(213) 555-3456",
    status: "active",
    views: 189,
    saves: 34,
    poster_name: "Тэмүүлэн Г.",
    poster_avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200",
    tags: ["iphone", "electronics", "la"],
    created_date: "2026-05-07T12:00:00Z"
  },
  {
    id: "mock-6",
    title: "Part-time Cashier - Mongolian Restaurant",
    description: "Looking for a part-time cashier for our Mongolian restaurant. Must speak Mongolian and English. Flexible hours. Монгол ресторанд кассчин авна.",
    category: "jobs",
    price: 17,
    price_type: "hourly",
    location_city: "Seattle",
    location_state: "WA",
    images: ["https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800"],
    status: "active",
    views: 98,
    saves: 12,
    poster_name: "Khaan's Kitchen",
    poster_avatar: "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200",
    job_company: "Khaan's Kitchen",
    job_salary_min: 17,
    job_salary_max: 20,
    job_type: "part-time",
    job_schedule: "Flexible, weekends required",
    tags: ["restaurant", "part-time", "seattle"],
    created_date: "2026-05-06T16:00:00Z"
  },
  {
    id: "mock-7",
    title: "Tax Preparation Service - Монгол хэлээр",
    description: "Professional tax preparation in Mongolian and English. Individual and business returns. Free consultation. IRS enrolled agent. Татварын үйлчилгээ Монгол хэлээр.",
    category: "services",
    price: 150,
    price_type: "fixed",
    location_city: "Virginia",
    location_state: "VA",
    images: ["https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800"],
    contact_phone: "(703) 555-7890",
    status: "active",
    is_featured: true,
    views: 445,
    saves: 67,
    poster_name: "Ганбаатар CPA",
    poster_avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200",
    tags: ["tax", "cpa", "mongolian", "virginia"],
    created_date: "2026-05-04T11:00:00Z"
  },
  {
    id: "mock-8",
    title: "2021 Honda Civic - Low Miles",
    description: "Clean title, one owner, regular maintenance. Great gas mileage. Цэвэр Honda Civic зарна.",
    category: "cars",
    price: 15000,
    price_type: "negotiable",
    location_city: "New York",
    location_state: "NY",
    images: ["https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800"],
    contact_phone: "(718) 555-2345",
    status: "active",
    views: 278,
    saves: 41,
    poster_name: "Батбаяр Н.",
    poster_avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    car_make: "Honda",
    car_model: "Civic",
    car_year: 2021,
    car_mileage: 28000,
    car_transmission: "automatic",
    car_fuel: "gasoline",
    car_condition: "excellent",
    tags: ["honda", "civic", "nyc"],
    created_date: "2026-05-07T15:00:00Z"
  },
  {
    id: "mock-9",
    title: "Room for Rent - Near Koreatown LA",
    description: "Private room in shared apartment. Near Koreatown. Close to buses and metro. Нэг өрөө түрээслүүлнэ.",
    category: "housing",
    price: 750,
    price_type: "monthly",
    location_city: "Los Angeles",
    location_state: "CA",
    images: ["https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    status: "active",
    views: 167,
    saves: 23,
    poster_name: "Оюунаа М.",
    poster_avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200",
    housing_bedrooms: 1,
    housing_bathrooms: 1,
    housing_furnished: true,
    housing_type: "room",
    housing_lease: "6 months",
    tags: ["room", "la", "koreatown"],
    created_date: "2026-05-06T09:00:00Z"
  },
  {
    id: "mock-10",
    title: "Mongolian BBQ Night - Community Event",
    description: "Monthly community BBQ gathering! Bring your family and friends. Free for all Mongolians! Сар бүрийн нийтийн шарсан мах.",
    category: "events",
    price: 0,
    price_type: "free",
    location_city: "Seattle",
    location_state: "WA",
    images: ["https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800"],
    status: "active",
    views: 432,
    saves: 78,
    poster_name: "Seattle Mongols",
    poster_avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=200",
    event_date: "2026-05-20T17:00:00Z",
    event_venue: "Woodland Park, Seattle",
    event_ticket_price: 0,
    event_organizer: "Seattle Mongolian Community",
    tags: ["bbq", "community", "seattle", "free"],
    created_date: "2026-05-03T10:00:00Z"
  }
];

export const MOCK_POSTS = [
  {
    id: "post-1",
    group_id: "grp-1",
    author_name: "Болд Б.",
    author_avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200",
    author_email: "bold@gmail.com",
    content: "Just arrived in Chicago! Looking for good Mongolian restaurants nearby. Suggestions?",
    image_url: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600",
    like_count: 45,
    comment_count: 12,
    repost_count: 3,
    type: "post",
    reactions: { "❤️": 25, "🔥": 20 },
    created_date: "2026-05-07T10:30:00Z"
  },
  {
    id: "post-2",
    group_id: "grp-2",
    author_name: "Батбаяр Н.",
    author_avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=200",
    author_email: "batbayar@gmail.com",
    content: "Best CDL companies to work for in 2026? Share your experiences!",
    like_count: 67,
    comment_count: 28,
    repost_count: 9,
    type: "post",
    reactions: { "👍": 45, "🚛": 22 },
    created_date: "2026-05-06T14:15:00Z"
  },
  {
    id: "post-3",
    group_id: "grp-3",
    author_name: "Сарнай Д.",
    author_avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200",
    author_email: "sarnai@gmail.com",
    content: "Community cleanup event this weekend! Free coffee and donuts for volunteers.",
    image_url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=600",
    like_count: 89,
    comment_count: 34,
    repost_count: 15,
    type: "post",
    reactions: { "❤️": 60, "👏": 29 },
    created_date: "2026-05-05T09:00:00Z"
  }
];

export const MOCK_GROUPS = [
  {
    id: "grp-1",
    name: "Chicago Mongolians",
    description: "The largest Mongolian community group in Chicago. Share news, events, jobs, and connect with fellow Mongolians. Чикагогийн Монголчуудын бүлэг.",
    cover_image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800",
    avatar: "🏙️",
    category: "community",
    city: "Chicago",
    member_count: 2847,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-2",
    name: "CDL Drivers USA - Монгол",
    description: "For Mongolian CDL drivers across the US. Share routes, companies, tips, and job openings. CDL жолоочдын бүлэг.",
    cover_image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800",
    avatar: "🚛",
    category: "professional",
    member_count: 1563,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-3",
    name: "Seattle Mongolian Community",
    description: "Connecting Mongolians in the Seattle/Tacoma area. Events, meetups, and community support. Сиатл Монголчууд.",
    cover_image: "https://images.unsplash.com/photo-1502175353174-a7a70e73b362?w=800",
    avatar: "🌲",
    category: "community",
    city: "Seattle",
    member_count: 892,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-4",
    name: "Mongolian Students USA",
    description: "Support network for Mongolian students studying in the US. Scholarships, advice, and networking. Монгол оюутнууд.",
    cover_image: "https://images.unsplash.com/photo-1523050854058-8df90110c476?w=800",
    avatar: "🎓",
    category: "education",
    member_count: 1245,
    is_verified: true,
    privacy: "public"
  },
  {
    id: "grp-5",
    name: "Mongolian Entrepreneurs",
    description: "Business owners and aspiring entrepreneurs. Share experiences, find partners, and grow together. Монгол бизнес эрхлэгчид.",
    cover_image: "https://images.unsplash.com/photo-1556761175-4b46a572b786?w=800",
    avatar: "💼",
    category: "business",
    member_count: 678,
    is_verified: false,
    privacy: "public"
  }
];

export const MOCK_BUSINESSES = [
  {
    id: "biz-1",
    name: "Khaan's Kitchen",
    description: "Authentic Mongolian restaurant serving traditional dishes. Buuz, khuushuur, tsuivan, and more. Жинхэнэ Монгол хоол.",
    category: "restaurant",
    logo: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=200",
    banner: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800",
    city: "Chicago",
    state: "IL",
    phone: "(312) 555-8888",
    hours: "Mon-Sat 11am-10pm, Sun 12pm-8pm",
    rating: 4.7,
    review_count: 234,
    is_verified: true,
    is_premium: true,
    tags: ["mongolian", "restaurant", "buuz"]
  },
  {
    id: "biz-2",
    name: "NomadTruck LLC",
    description: "Mongolian-owned trucking company. OTR and regional routes. Always hiring CDL-A drivers with good pay and benefits.",
    category: "trucking",
    logo: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=200",
    banner: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800",
    city: "Chicago",
    state: "IL",
    phone: "(773) 555-5678",
    hours: "Mon-Fri 8am-6pm",
    rating: 4.3,
    review_count: 89,
    is_verified: true,
    is_premium: true,
    tags: ["trucking", "cdl", "jobs"]
  },
  {
    id: "biz-3",
    name: "Ганбаатар CPA Services",
    description: "Full-service accounting and tax preparation. Mongolian and English speaking. Individual and business returns.",
    category: "tax",
    logo: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=200",
    banner: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800",
    city: "Virginia",
    state: "VA",
    phone: "(703) 555-7890",
    hours: "Mon-Fri 9am-5pm, Sat by appointment",
    rating: 4.9,
    review_count: 156,
    is_verified: true,
    is_premium: false,
    tags: ["tax", "cpa", "accounting"]
  },
  {
    id: "biz-4",
    name: "Nomad Beauty Salon",
    description: "Premium beauty salon specializing in Asian hair care. Mongolian owned and operated. Гоо сайхны салон.",
    category: "salon",
    logo: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=200",
    banner: "https://images.unsplash.com/photo-1521590832167-7bcbfaa6381f?w=800",
    city: "Los Angeles",
    state: "CA",
    phone: "(213) 555-4567",
    hours: "Tue-Sun 10am-7pm",
    rating: 4.6,
    review_count: 78,
    is_verified: true,
    is_premium: true,
    tags: ["salon", "beauty", "hair"]
  },
  {
    id: "biz-5",
    name: "Blue Mountain Trading",
    description: "Import/export goods from Mongolia. Traditional crafts and modern goods. Монголын бүтээгдэхүүн.",
    category: "retail",
    logo: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=200",
    banner: "https://images.unsplash.com/photo-1441984904556-0b8b8b6a8a8b?w=800",
    city: "New York",
    state: "NY",
    phone: "(212) 555-1234",
    hours: "Daily 10am-8pm",
    rating: 4.4,
    review_count: 62,
    is_verified: true,
    is_premium: false,
    tags: ["import", "mongolian", "crafts"]
  },
  {
    id: "biz-6",
    name: "Nomad Healthcare",
    description: "Bilingual healthcare clinic serving Mongolian families. Монголчуудын эрүүлийн төв.",
    category: "healthcare",
    logo: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200",
    banner: "https://images.unsplash.com/photo-1631217314831-c6227db76b6e?w=800",
    city: "Houston",
    state: "TX",
    phone: "(713) 555-9999",
    hours: "Mon-Fri 8am-6pm, Sat 9am-2pm",
    rating: 4.8,
    review_count: 145,
    is_verified: true,
    is_premium: true,
    tags: ["healthcare", "bilingual", "clinic"]
  }
];

export const CATEGORIES = [
  { id: "jobs", label: "Jobs", labelMn: "Ажил", icon: "Briefcase" },
  { id: "housing", label: "Housing", labelMn: "Байр", icon: "Home" },
  { id: "events", label: "Events", labelMn: "Арга хэмжээ", icon: "Calendar" },
  { id: "cars", label: "Cars", labelMn: "Машин", icon: "Car" },
  { id: "services", label: "Services", labelMn: "Үйлчилгээ", icon: "Wrench" },
  { id: "electronics", label: "Electronics", labelMn: "Электроник", icon: "Smartphone" },
  { id: "community", label: "Community", labelMn: "Нийгэмлэг", icon: "Users" }
];

export const ICONS = {
  Car: "🚗",
  Briefcase: "💼",
  Home: "🏠",
  Wrench: "🔧",
  Calendar: "📅",
  Smartphone: "📱",
  Users: "👥",
  globe: "🌍"
};

export const TRENDING_SEARCHES = [
  "CDL ажил Chicago",
  "apartment near me",
  "Монгол ресторан",
  "part time job",
  "машин зарна",
  "room for rent LA",
  "trucking company",
  "tax preparation"
];

export const CITIES = [
  { name: "Chicago", state: "IL", count: 1245 },
  { name: "Los Angeles", state: "CA", count: 876 },
  { name: "Seattle", state: "WA", count: 543 },
  { name: "New York", state: "NY", count: 432 },
  { name: "Virginia", state: "VA", count: 321 },
  { name: "Korea", state: "", count: 234 },
  { name: "Europe", state: "", count: 187 },
  { name: "Houston", state: "TX", count: 892 },
  { name: "Phoenix", state: "AZ", count: 654 },
  { name: "Philadelphia", state: "PA", count: 567 },
  { name: "San Antonio", state: "TX", count: 432 },
  { name: "San Diego", state: "CA", count: 789 },
  { name: "Dallas", state: "TX", count: 923 },
  { name: "San Jose", state: "CA", count: 543 },
  { name: "Austin", state: "TX", count: 678 },
  { name: "Jacksonville", state: "FL", count: 456 },
  { name: "Denver", state: "CO", count: 612 },
  { name: "Boston", state: "MA", count: 834 },
  { name: "Las Vegas", state: "NV", count: 345 },
  { name: "Minneapolis", state: "MN", count: 567 },
  { name: "Nashville", state: "TN", count: 489 },
  { name: "Atlanta", state: "GA", count: 721 },
  { name: "Portland", state: "OR", count: 534 },
  { name: "Miami", state: "FL", count: 678 },
  { name: "Detroit", state: "MI", count: 456 },
  { name: "Baltimore", state: "MD", count: 389 },
  { name: "Louisville", state: "KY", count: 267 },
  { name: "Milwaukee", state: "WI", count: 398 },
  { name: "Albuquerque", state: "NM", count: 234 },
  { name: "Tucson", state: "AZ", count: 178 },
  { name: "Sacramento", state: "CA", count: 321 },
  { name: "Cleveland", state: "OH", count: 289 },
  { name: "Columbus", state: "OH", count: 445 },
  { name: "Mesa", state: "AZ", count: 212 },
  { name: "Arlington", state: "TX", count: 334 },
  { name: "Bakersfield", state: "CA", count: 189 },
  { name: "Long Beach", state: "CA", count: 276 },
  { name: "Anaheim", state: "CA", count: 198 },
  { name: "Irving", state: "TX", count: 267 },
  { name: "Oakland", state: "CA", count: 345 },
  { name: "Stockton", state: "CA", count: 156 },
  { name: "Saint Paul", state: "MN", count: 287 },
  { name: "Saint Louis", state: "MO", count: 423 },
  { name: "Riverside", state: "CA", count: 298 },
  { name: "Irvine", state: "CA", count: 267 },
  { name: "Corpus Christi", state: "TX", count: 178 },
  { name: "Lexington", state: "KY", count: 234 },
  { name: "Plano", state: "TX", count: 289 },
  { name: "Chandler", state: "AZ", count: 156 },
  { name: "Garland", state: "TX", count: 198 },
  { name: "Durham", state: "NC", count: 267 },
  { name: "Laredo", state: "TX", count: 134 },
  { name: "Henderson", state: "NV", count: 178 },
  { name: "Lubbock", state: "TX", count: 145 },
  { name: "Winston-Salem", state: "NC", count: 189 },
  { name: "Norfolk", state: "VA", count: 212 },
  { name: "Greensboro", state: "NC", count: 223 },
  { name: "Chula Vista", state: "CA", count: 156 },
  { name: "Madison", state: "WI", count: 234 },
  { name: "Baton Rouge", state: "LA", count: 267 },
  { name: "Birmingham", state: "AL", count: 189 },
  { name: "Huntsville", state: "AL", count: 145 },
  { name: "Tallahassee", state: "FL", count: 167 },
  { name: "New Orleans", state: "LA", count: 398 },
  { name: "Montgomery", state: "AL", count: 123 },
  { name: "Memphis", state: "TN", count: 345 },
  { name: "Fresno", state: "CA", count: 278 },
  { name: "Worcester", state: "MA", count: 198 },
  { name: "Providence", state: "RI", count: 156 },
  { name: "Hartford", state: "CT", count: 134 },
  { name: "Richmond", state: "VA", count: 289 },
  { name: "Jacksonville", state: "NC", count: 112 },
  { name: "Moreno Valley", state: "CA", count: 98 },
  { name: "Oxnard", state: "CA", count: 145 },
  { name: "Ontario", state: "CA", count: 167 },
  { name: "Fontana", state: "CA", count: 123 },
  { name: "Brownsville", state: "TX", count: 89 },
  { name: "Modesto", state: "CA", count: 156 },
  { name: "Glendale", state: "AZ", count: 134 },
  { name: "Santa Ana", state: "CA", count: 189 },
  { name: "Akron", state: "OH", count: 145 },
  { name: "Toledo", state: "OH", count: 167 },
  { name: "Shreveport", state: "LA", count: 98 },
  { name: "Aurora", state: "CO", count: 212 },
  { name: "Spokane", state: "WA", count: 187 },
  { name: "Visalia", state: "CA", count: 145 },
  { name: "Garland", state: "TX", count: 167 },
  { name: "Montreal", state: "QC", count: 298 },
  { name: "Toronto", state: "ON", count: 356 },
  { name: "Vancouver", state: "BC", count: 267 }
];

export const VIP_BOOST_PACKAGES = [
  {
    id: "vip-basic",
    name: "Basic Boost",
    price: 4.99,
    duration_days: 7,
    features: ["Top placement", "250 extra views"],
    color: "blue"
  },
  {
    id: "vip-pro",
    name: "Pro Boost",
    price: 9.99,
    duration_days: 14,
    features: ["Premium placement", "1000 extra views", "Featured badge"],
    color: "purple",
    popular: true
  },
  {
    id: "vip-premium",
    name: "Premium Boost",
    price: 24.99,
    duration_days: 30,
    features: ["Maximum visibility", "5000 extra views", "Featured badge", "Priority support"],
    color: "gold"
  }
];